apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pf-status-relay-operator-pf-status-relay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pf-status-relay-operator-pf-status-relay
subjects:
- kind: ServiceAccount
  name: pf-status-relay-operator-pf-status-relay
  namespace: openshift-pf-status-relay-operator
