---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pfstatusrelay-openshift-io-v1alpha1-pflacpmonitor
  failurePolicy: Fail
  name: vpflacpmonitor.kb.io
  rules:
  - apiGroups:
    - pfstatusrelay.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pflacpmonitors
  sideEffects: None
