---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pf-status-relay-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pf-status-relay-role
subjects:
  - kind: ServiceAccount
    name: pf-status-relay-sa
    namespace: system
