---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - pfstatusrelay.openshift.io
  resources:
  - pflacpmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pfstatusrelay.openshift.io
  resources:
  - pflacpmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - pfstatusrelay.openshift.io
  resources:
  - pflacpmonitors/status
  verbs:
  - get
  - patch
  - update
